### ISSUE TITLE
Inconsistent tuple types

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#114]
```
-- This is OK, (Int, String) is a type
let fn1 (x : (Int, String)) = (x._1, x._2);

-- But () is not a type
let fn2 (x : ()) = ();
             ^----- Compiler reports a parse error here
```

I know the type of `()` is `Unit`, but shouldn't we unify all of them?

**Comment by zhiyuanshi** [comment]
We take the Scala approach: `()` vs `Unit`.

**Comment by zonyitoo** [comment]
@zhiyuanshi I would prefer Haskell's style, use `()` as the type of `()`.

**Comment by bixuanzju** [comment]
@zonyitoo (I am taking the role of issue manager now) Let's settle this issue by saying that since our language is targeting Java, we want every type name corresponds to a Java Class or Interface. `Unit` is a sensible name for Java `Void` Class. Besides, since we use square brackets `[]` for type application, personally I find something like `id[()] ()` quite strange. 

Anyway, this is mostly a matter of taste, and obviously we cannot please every one in terms of syntax. If you don't mind, I would like to close it?

**Comment by zonyitoo** [comment]
@bixuanzju Alright
